### ISSUE TITLE
Execution problem with 0.1.1 version

### ISSUE THREAD

**Issue by jmartinezs77** [fjhorrillo/homebridge-airzone-cloud#5]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

Please find log in the image attached

Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.1.1
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by fjhorrillo** [comment]
Hello! Could you provide some info about the problem?

**Comment by jmartinezs77** [comment]
Everything was working and I saw an available upgrade of you plug-in, I executed it and on relaunch everything zone dissapeared. I searched the logs and I found some issues. I send you more detail.
I have tried to go back to version 0.1.0 and the issue remains the same. Not clear what is happening. 
please tell me if you need something more specific.
Here is de log:
[4/3/2021, 7:11:42 PM] [Homebridge UI] Running Command: npm install --save homebridge-airzone-cloud@latest
[4/3/2021, 7:12:09 PM] [Homebridge UI] Running Command: npm install --save homebridge-zp@latest
[4/3/2021, 7:12:21 PM] [Homebridge UI] Homebridge restart request received
[4/3/2021, 7:12:21 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[4/3/2021, 7:12:21 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[4/3/2021, 7:12:21 PM] Got SIGTERM, shutting down Homebridge...
[4/3/2021, 7:12:26 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/3/2021, 7:12:31 PM] [HB Supervisor] Restarting Homebridge...
[4/3/2021, 7:12:31 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[4/3/2021, 7:12:32 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 31342
Initializing HAP-NodeJS v0.9.4...
[4/3/2021, 7:12:32 PM] Loaded config.json with 1 accessories and 6 platforms.
[4/3/2021, 7:12:32 PM] Loaded 10 cached accessories from cachedAccessories.
[4/3/2021, 7:12:32 PM] ---
[4/3/2021, 7:12:33 PM] ====================
[4/3/2021, 7:12:33 PM] ERROR LOADING PLUGIN homebridge-airzone-cloud:
[4/3/2021, 7:12:33 PM] Error: Cannot find module 'homebridge/lib/logger'
Require stack:
- /homebridge/node_modules/homebridge-airzone-cloud/dist/platform.js
- /homebridge/node_modules/homebridge-airzone-cloud/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[4/3/2021, 7:12:33 PM] ====================
[4/3/2021, 7:12:33 PM] Loaded plugin: homebridge-connexoon@2.1.1
[4/3/2021, 7:12:33 PM] Registering platform 'homebridge-connexoon.Connexoon'
[4/3/2021, 7:12:33 PM] ---
[4/3/2021, 7:12:33 PM] Disabled plugin: homebridge-dummy@0.5.0
[4/3/2021, 7:12:33 PM] ---
[4/3/2021, 7:12:33 PM] Loaded plugin: homebridge-mi-humidifier@2.3.1
[4/3/2021, 7:12:33 PM] Registering platform 'homebridge-mi-humidifier.MiHumidifier'
[4/3/2021, 7:12:33 PM] ---
[4/3/2021, 7:12:33 PM] Disabled plugin: homebridge-nest@4.5.3
[4/3/2021, 7:12:33 PM] ---
[4/3/2021, 7:12:33 PM] Disabled plugin: homebridge-xiaomi-mi-air-purifier@1.1.0
[4/3/2021, 7:12:33 PM] ---
[4/3/2021, 7:12:33 PM] Disabled plugin: homebridge-zp@1.2.1
[4/3/2021, 7:12:33 PM] ---
[4/3/2021, 7:12:33 PM] Loaded plugin: homebridge-config-ui-x@4.41.0
[4/3/2021, 7:12:33 PM] Registering platform 'homebridge-config-ui-x.config'
[4/3/2021, 7:12:33 PM] ---
[4/3/2021, 7:12:33 PM] Loading 6 platforms...
[4/3/2021, 7:12:33 PM] [Config] Initializing config platform...
[4/3/2021, 7:12:33 PM] [Config] Running in Service Mode
[4/3/2021, 7:12:33 PM] Ignoring config for the platform "Nest" in your config.json as the plugin "homebridge-nest" has been disabled.
[4/3/2021, 7:12:33 PM] [MiHumidifier] Initializing MiHumidifier platform...
[4/3/2021, 7:12:33 PM] [My Connexoon Hub] Initializing Connexoon platform...
[4/3/2021, 7:12:33 PM] [My Connexoon Hub] Connexoon Init
[4/3/2021, 7:12:33 PM] Ignoring config for the platform "ZP" in your config.json as the plugin "homebridge-zp" has been disabled.
[4/3/2021, 7:12:33 PM] No plugin was found for the platform "AirzoneCloud" in your config.json. Please make sure the corresponding plugin is installed correctly.
[4/3/2021, 7:12:33 PM] Loading 1 accessories...
[4/3/2021, 7:12:33 PM] Ignoring config for the accessory "XiaomiMiAirPurifier" in your config.json as the plugin "homebridge-xiaomi-mi-air-purifier" has been disabled.
[4/3/2021, 7:12:33 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Firmware Revision': Characteristic not in required or optional characteristic section for service AccessoryInformation. Adding anyway.. See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:33 PM] [My Connexoon Hub] Restoring cached accessory Persiana Salón Derecha
[4/3/2021, 7:12:33 PM] [My Connexoon Hub] Restoring cached accessory Persiana Dormitorio
[4/3/2021, 7:12:33 PM] [My Connexoon Hub] Restoring cached accessory Persiana Salón Izquierda
[4/3/2021, 7:12:33 PM] Failed to find plugin to handle accessory COCINA2    
[4/3/2021, 7:12:33 PM] Removing orphaned accessory COCINA2    
[4/3/2021, 7:12:33 PM] Failed to find plugin to handle accessory DPCHO-Z5   
[4/3/2021, 7:12:33 PM] Removing orphaned accessory DPCHO-Z5   
[4/3/2021, 7:12:33 PM] Failed to find plugin to handle accessory HAB CHUR-Z4
[4/3/2021, 7:12:33 PM] Removing orphaned accessory HAB CHUR-Z4
[4/3/2021, 7:12:33 PM] Failed to find plugin to handle accessory HAB PRAL-Z6
[4/3/2021, 7:12:33 PM] Removing orphaned accessory HAB PRAL-Z6
[4/3/2021, 7:12:33 PM] Failed to find plugin to handle accessory HAB-M30-Z3 
[4/3/2021, 7:12:33 PM] Removing orphaned accessory HAB-M30-Z3 
[4/3/2021, 7:12:33 PM] Failed to find plugin to handle accessory SALON1     
[4/3/2021, 7:12:33 PM] Removing orphaned accessory SALON1     
Preparing Advertiser for 'Homebridge 8518 62D6' using bonjour-hap backend!
Setup Payload:
X-HM://0023ISYWYCW7Q
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 8518 62D6' using bonjour-hap backend!
[4/3/2021, 7:12:33 PM] Homebridge v1.3.4 (Homebridge 8518) is running on port 51773.
[4/3/2021, 7:12:34 PM] [My Connexoon Hub] Starting polling for Connexoon accessory state every 10 minute(s)
[4/3/2021, 7:12:34 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:34 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Water Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:34 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:34 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:34 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:34 PM] [My Connexoon Hub] Get Persiana Salón Derecha current position success: 0
[4/3/2021, 7:12:34 PM] [My Connexoon Hub] Get Persiana Salón Derecha target position success: 0
[4/3/2021, 7:12:34 PM] [My Connexoon Hub] Get Persiana Dormitorio current position success: 0
[4/3/2021, 7:12:34 PM] [My Connexoon Hub] Get Persiana Dormitorio target position success: 0
[4/3/2021, 7:12:34 PM] [My Connexoon Hub] Get Persiana Salón Izquierda current position success: 0
[4/3/2021, 7:12:34 PM] [My Connexoon Hub] Get Persiana Salón Izquierda target position success: 0
[4/3/2021, 7:12:35 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:35 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Water Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:35 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:35 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:35 PM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/3/2021, 7:12:35 PM] [My Connexoon Hub] Get Persiana Salón Derecha current position success: 100
[4/3/2021, 7:12:35 PM] [My Connexoon Hub] Get Persiana Salón Derecha target position success: 100
[4/3/2021, 7:12:35 PM] [My Connexoon Hub] Get Persiana Dormitorio current position success: 100
[4/3/2021, 7:12:35 PM] [My Connexoon Hub] Get Persiana Dormitorio target position success: 100
[4/3/2021, 7:12:35 PM] [My Connexoon Hub] Get Persiana Salón Izquierda current position success: 0
[4/3/2021, 7:12:35 PM] [My Connexoon Hub] Get Persiana Salón Izquierda target position success: 0
[4/3/2021, 7:12:38 PM] [My Connexoon Hub] Get Persiana Salón Derecha current position success: 100
[4/3/2021, 7:12:38 PM] [My Connexoon Hub] Get Persiana Salón Derecha target position success: 100
[4/3/2021, 7:12:38 PM] [My Connexoon Hub] Get Persiana Dormitorio current position success: 100
[4/3/2021, 7:12:38 PM] [My Connexoon Hub] Get Persiana Dormitorio target position success: 100
[4/3/2021, 7:12:38 PM] [My Connexoon Hub] Get Persiana Salón Izquierda current position success: 0
[4/3/2021, 7:12:38 PM] [My Connexoon Hub] Get Persiana Salón Izquierda target position success: 0

**Comment by fjhorrillo** [comment]
Hello, the error is related to the new way to manage logs, it was added in 0.1.0.
Could you remove the plugin, and add it again, its look like some dependency from homebridge are missing

**Comment by jmartinezs77** [comment]
I have already tried reinstalling version 0.1.0 and 0.1.1 and the problem persist. Maybe an older version?

**Comment by fjhorrillo** [comment]
Yes, the version you probably have before was 0.0.2

**Comment by fjhorrillo** [comment]
Fixed in version 0.1.2

**Comment by jmartinezs77** [comment]
Hi,
0.1.2 doesn’t fix the bug. It still generates the same issues.
I tried various things:
- updating from 0.1.1
- Uninstalling and installing 0.1.2
- Uninstalling, installing 0.0.2 and updating to 0.1.2
None of them worked.
Finally I installed 0.0.2 and this version installed and launched without issues.
Thank you!!

**Comment by fjhorrillo** [comment]
Hi! Could you share the error with this version, and also your configuration for the plugin? If you don’t use the debug option with this version should be work

**Comment by jmartinezs77** [comment]
Goof morning, 

here is the log and I attach some screen captures with configuration of hombridge and of the plug-in.

thanks


[4/4/2021, 9:19:37 AM] [Homebridge UI] Changes to config.json saved.
[4/4/2021, 9:19:40 AM] [Homebridge UI] Homebridge restart request received
[4/4/2021, 9:19:40 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[4/4/2021, 9:19:40 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[4/4/2021, 9:19:40 AM] Got SIGTERM, shutting down Homebridge...
[4/4/2021, 9:19:45 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/4/2021, 9:19:50 AM] [HB Supervisor] Restarting Homebridge...
[4/4/2021, 9:19:50 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[4/4/2021, 9:19:50 AM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 6574
Initializing HAP-NodeJS v0.9.4...
[4/4/2021, 9:19:50 AM] Loaded config.json with 1 accessories and 6 platforms.
[4/4/2021, 9:19:50 AM] Loaded 4 cached accessories from cachedAccessories.
[4/4/2021, 9:19:50 AM] ---
[4/4/2021, 9:19:51 AM] ====================
[4/4/2021, 9:19:51 AM] ERROR LOADING PLUGIN homebridge-airzone-cloud:
[4/4/2021, 9:19:51 AM] Error: Cannot find module 'homebridge/lib/logger'
Require stack:
- /homebridge/node_modules/homebridge-airzone-cloud/dist/platform.js
- /homebridge/node_modules/homebridge-airzone-cloud/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[4/4/2021, 9:19:51 AM] ====================
[4/4/2021, 9:19:51 AM] Loaded plugin: homebridge-connexoon@2.1.1
[4/4/2021, 9:19:51 AM] Registering platform 'homebridge-connexoon.Connexoon'
[4/4/2021, 9:19:51 AM] ---
[4/4/2021, 9:19:51 AM] Disabled plugin: homebridge-dummy@0.5.0
[4/4/2021, 9:19:51 AM] ---
[4/4/2021, 9:19:51 AM] Loaded plugin: homebridge-mi-humidifier@2.3.1
[4/4/2021, 9:19:51 AM] Registering platform 'homebridge-mi-humidifier.MiHumidifier'
[4/4/2021, 9:19:51 AM] ---
[4/4/2021, 9:19:51 AM] Disabled plugin: homebridge-nest@4.5.3
[4/4/2021, 9:19:51 AM] ---
[4/4/2021, 9:19:51 AM] Disabled plugin: homebridge-xiaomi-mi-air-purifier@1.1.0
[4/4/2021, 9:19:51 AM] ---
[4/4/2021, 9:19:51 AM] Disabled plugin: homebridge-zp@1.2.1
[4/4/2021, 9:19:51 AM] ---
[4/4/2021, 9:19:51 AM] Loaded plugin: homebridge-config-ui-x@4.41.0
[4/4/2021, 9:19:51 AM] Registering platform 'homebridge-config-ui-x.config'
[4/4/2021, 9:19:51 AM] ---
[4/4/2021, 9:19:51 AM] Loading 6 platforms...
[4/4/2021, 9:19:51 AM] [Config] Initializing config platform...
[4/4/2021, 9:19:51 AM] [Config] Running in Service Mode
[4/4/2021, 9:19:51 AM] Ignoring config for the platform "Nest" in your config.json as the plugin "homebridge-nest" has been disabled.
[4/4/2021, 9:19:51 AM] [MiHumidifier] Initializing MiHumidifier platform...
[4/4/2021, 9:19:51 AM] [My Connexoon Hub] Initializing Connexoon platform...
[4/4/2021, 9:19:51 AM] [My Connexoon Hub] Connexoon Init
[4/4/2021, 9:19:51 AM] Ignoring config for the platform "ZP" in your config.json as the plugin "homebridge-zp" has been disabled.
[4/4/2021, 9:19:51 AM] No plugin was found for the platform "AirzoneCloud" in your config.json. Please make sure the corresponding plugin is installed correctly.
[4/4/2021, 9:19:51 AM] Loading 1 accessories...
[4/4/2021, 9:19:51 AM] Ignoring config for the accessory "XiaomiMiAirPurifier" in your config.json as the plugin "homebridge-xiaomi-mi-air-purifier" has been disabled.
[4/4/2021, 9:19:51 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Firmware Revision': Characteristic not in required or optional characteristic section for service AccessoryInformation. Adding anyway.. See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:51 AM] [My Connexoon Hub] Restoring cached accessory Persiana Salón Derecha
[4/4/2021, 9:19:51 AM] [My Connexoon Hub] Restoring cached accessory Persiana Dormitorio
[4/4/2021, 9:19:51 AM] [My Connexoon Hub] Restoring cached accessory Persiana Salón Izquierda
Preparing Advertiser for 'Homebridge 8518 62D6' using bonjour-hap backend!
Setup Payload:
X-HM://0023ISYWYCW7Q
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 8518 62D6' using bonjour-hap backend!
[4/4/2021, 9:19:52 AM] Homebridge v1.3.4 (Homebridge 8518) is running on port 51773.
[4/4/2021, 9:19:52 AM] [My Connexoon Hub] Starting polling for Connexoon accessory state every 10 minute(s)
[4/4/2021, 9:19:52 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:52 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Water Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:52 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:52 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:52 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:52 AM] [My Connexoon Hub] Get Persiana Salón Derecha current position success: 0
[4/4/2021, 9:19:52 AM] [My Connexoon Hub] Get Persiana Salón Derecha target position success: 0
[4/4/2021, 9:19:52 AM] [My Connexoon Hub] Get Persiana Dormitorio current position success: 0
[4/4/2021, 9:19:52 AM] [My Connexoon Hub] Get Persiana Dormitorio target position success: 0
[4/4/2021, 9:19:52 AM] [My Connexoon Hub] Get Persiana Salón Izquierda current position success: 0
[4/4/2021, 9:19:52 AM] [My Connexoon Hub] Get Persiana Salón Izquierda target position success: 0
[4/4/2021, 9:19:53 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:53 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Water Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:53 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:53 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:53 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:19:53 AM] [My Connexoon Hub] Get Persiana Salón Derecha current position success: 50
[4/4/2021, 9:19:53 AM] [My Connexoon Hub] Get Persiana Salón Derecha target position success: 50
[4/4/2021, 9:19:53 AM] [My Connexoon Hub] Get Persiana Dormitorio current position success: 0
[4/4/2021, 9:19:53 AM] [My Connexoon Hub] Get Persiana Dormitorio target position success: 0
[4/4/2021, 9:19:53 AM] [My Connexoon Hub] Get Persiana Salón Izquierda current position success: 50
[4/4/2021, 9:19:53 AM] [My Connexoon Hub] Get Persiana Salón Izquierda target position success: 50
[4/4/2021, 9:20:20 AM] [My Connexoon Hub] Get Persiana Salón Derecha current position success: 50
[4/4/2021, 9:20:20 AM] [My Connexoon Hub] Get Persiana Salón Derecha target position success: 50
[4/4/2021, 9:20:20 AM] [My Connexoon Hub] Get Persiana Dormitorio current position success: 0
[4/4/2021, 9:20:20 AM] [My Connexoon Hub] Get Persiana Dormitorio target position success: 0
[4/4/2021, 9:20:20 AM] [My Connexoon Hub] Get Persiana Salón Izquierda current position success: 50
[4/4/2021, 9:20:20 AM] [My Connexoon Hub] Get Persiana Salón Izquierda target position success: 50
[4/4/2021, 9:20:21 AM] [Homebridge UI] Changes to config.json saved.
[4/4/2021, 9:20:29 AM] [Homebridge UI] Homebridge restart request received
[4/4/2021, 9:20:29 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[4/4/2021, 9:20:29 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[4/4/2021, 9:20:29 AM] Got SIGTERM, shutting down Homebridge...
[4/4/2021, 9:20:34 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/4/2021, 9:20:39 AM] [HB Supervisor] Restarting Homebridge...
[4/4/2021, 9:20:39 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[4/4/2021, 9:20:39 AM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 6635
Initializing HAP-NodeJS v0.9.4...
[4/4/2021, 9:20:40 AM] Loaded config.json with 1 accessories and 6 platforms.
[4/4/2021, 9:20:40 AM] Loaded 4 cached accessories from cachedAccessories.
[4/4/2021, 9:20:40 AM] ---
[4/4/2021, 9:20:40 AM] ====================
[4/4/2021, 9:20:40 AM] ERROR LOADING PLUGIN homebridge-airzone-cloud:
[4/4/2021, 9:20:40 AM] Error: Cannot find module 'homebridge/lib/logger'
Require stack:
- /homebridge/node_modules/homebridge-airzone-cloud/dist/platform.js
- /homebridge/node_modules/homebridge-airzone-cloud/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-airzone-cloud/src/platform.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[4/4/2021, 9:20:40 AM] ====================
[4/4/2021, 9:20:40 AM] Loaded plugin: homebridge-connexoon@2.1.1
[4/4/2021, 9:20:40 AM] Registering platform 'homebridge-connexoon.Connexoon'
[4/4/2021, 9:20:40 AM] ---
[4/4/2021, 9:20:40 AM] Disabled plugin: homebridge-dummy@0.5.0
[4/4/2021, 9:20:40 AM] ---
[4/4/2021, 9:20:40 AM] Loaded plugin: homebridge-mi-humidifier@2.3.1
[4/4/2021, 9:20:40 AM] Registering platform 'homebridge-mi-humidifier.MiHumidifier'
[4/4/2021, 9:20:40 AM] ---
[4/4/2021, 9:20:40 AM] Disabled plugin: homebridge-nest@4.5.3
[4/4/2021, 9:20:40 AM] ---
[4/4/2021, 9:20:41 AM] Disabled plugin: homebridge-xiaomi-mi-air-purifier@1.1.0
[4/4/2021, 9:20:41 AM] ---
[4/4/2021, 9:20:41 AM] Disabled plugin: homebridge-zp@1.2.1
[4/4/2021, 9:20:41 AM] ---
[4/4/2021, 9:20:41 AM] Loaded plugin: homebridge-config-ui-x@4.41.0
[4/4/2021, 9:20:41 AM] Registering platform 'homebridge-config-ui-x.config'
[4/4/2021, 9:20:41 AM] ---
[4/4/2021, 9:20:41 AM] Loading 6 platforms...
[4/4/2021, 9:20:41 AM] [Config] Initializing config platform...
[4/4/2021, 9:20:41 AM] [Config] Running in Service Mode
[4/4/2021, 9:20:41 AM] Ignoring config for the platform "Nest" in your config.json as the plugin "homebridge-nest" has been disabled.
[4/4/2021, 9:20:41 AM] [MiHumidifier] Initializing MiHumidifier platform...
[4/4/2021, 9:20:41 AM] [My Connexoon Hub] Initializing Connexoon platform...
[4/4/2021, 9:20:41 AM] [My Connexoon Hub] Connexoon Init
[4/4/2021, 9:20:41 AM] Ignoring config for the platform "ZP" in your config.json as the plugin "homebridge-zp" has been disabled.
[4/4/2021, 9:20:41 AM] No plugin was found for the platform "AirzoneCloud" in your config.json. Please make sure the corresponding plugin is installed correctly.
[4/4/2021, 9:20:41 AM] Loading 1 accessories...
[4/4/2021, 9:20:41 AM] Ignoring config for the accessory "XiaomiMiAirPurifier" in your config.json as the plugin "homebridge-xiaomi-mi-air-purifier" has been disabled.
[4/4/2021, 9:20:41 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Firmware Revision': Characteristic not in required or optional characteristic section for service AccessoryInformation. Adding anyway.. See https://git.io/JtMGR for more info.
[4/4/2021, 9:20:41 AM] [My Connexoon Hub] Restoring cached accessory Persiana Salón Derecha
[4/4/2021, 9:20:41 AM] [My Connexoon Hub] Restoring cached accessory Persiana Dormitorio
[4/4/2021, 9:20:41 AM] [My Connexoon Hub] Restoring cached accessory Persiana Salón Izquierda
Preparing Advertiser for 'Homebridge 8518 62D6' using bonjour-hap backend!
Setup Payload:
X-HM://0023ISYWYCW7Q
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 8518 62D6' using bonjour-hap backend!
[4/4/2021, 9:20:41 AM] Homebridge v1.3.4 (Homebridge 8518) is running on port 51773.
[4/4/2021, 9:20:41 AM] [My Connexoon Hub] Starting polling for Connexoon accessory state every 10 minute(s)
[4/4/2021, 9:20:42 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:20:42 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Water Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[4/4/2021, 9:20:42 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:20:42 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/4/2021, 9:20:42 AM] [homebridge-mi-humidifier] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info
![53071B81-1372-41DA-B870-50AAB2233EBA](https://user-images.githubusercontent.com/81236858/113501829-64f5e880-9528-11eb-96e8-fd3603750bdf.jpeg)
![A95DEC06-3E50-4031-A7DB-4829C4B51F75](https://user-images.githubusercontent.com/81236858/113501833-67584280-9528-11eb-9a6c-25809447afef.jpeg)
![B5BE46AB-1198-4B8C-9ABE-2DA111800B5A](https://user-images.githubusercontent.com/81236858/113501835-67f0d900-9528-11eb-8909-aa011d885ec3.jpeg)

**Comment by fjhorrillo** [comment]
Fixed in version 0.1.3

**Comment by jmartinezs77** [comment]
Just updated to 0.1.3 and everything up & running smoothly.
Many thanks!
